// Copyright 2018 The go-libvirt Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// Code generated by internal/lvgen/generate.go. DO NOT EDIT.
//
// To regenerate, run 'go generate' in internal/lvgen.
//

package constants

// These are libvirt procedure numbers which correspond to each respective
// API call between remote_internal driver and libvirtd. Each procedure is
// identified by a unique number.
const (
	// From enums:
	// QemuProcDomainMonitorCommand is libvirt's QEMU_PROC_DOMAIN_MONITOR_COMMAND
	QemuProcDomainMonitorCommand = 1
	// QemuProcDomainAttach is libvirt's QEMU_PROC_DOMAIN_ATTACH
	QemuProcDomainAttach = 2
	// QemuProcDomainAgentCommand is libvirt's QEMU_PROC_DOMAIN_AGENT_COMMAND
	QemuProcDomainAgentCommand = 3
	// QemuProcConnectDomainMonitorEventRegister is libvirt's QEMU_PROC_CONNECT_DOMAIN_MONITOR_EVENT_REGISTER
	QemuProcConnectDomainMonitorEventRegister = 4
	// QemuProcConnectDomainMonitorEventDeregister is libvirt's QEMU_PROC_CONNECT_DOMAIN_MONITOR_EVENT_DEREGISTER
	QemuProcConnectDomainMonitorEventDeregister = 5
	// QemuProcDomainMonitorEvent is libvirt's QEMU_PROC_DOMAIN_MONITOR_EVENT
	QemuProcDomainMonitorEvent = 6


	// From consts:
	// QemuProgram is libvirt's QEMU_PROGRAM
	QemuProgram = 0x20008087
	// QemuProtocolVersion is libvirt's QEMU_PROTOCOL_VERSION
	QemuProtocolVersion = 1
)
